spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio_advisor
    username: pa3553
    password: pa12345!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    user:
      name: pa3553
      password: 12345
  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0.0
    clean-on-validation-error: false
    out-of-order: false
    locations:
      - db/migration

logging:
  level:
    root: info